
export const SEARCH_PLACE = 'SEARCH_PLACE'
export const SEARCH_PLACE_SUCCESS = 'SEARCH_PLACE_SUCCESS'
export const SEARCH_PLACE_ERROR = 'SEARCH_PLACE_ERROR'
export const ON_FETCH_PLACES = 'ON_FETCH_PLACES'
export const ON_SHOW_SUGGESTION = 'ON_SHOW_SUGGESTION'
export const ON_CLICK_OUTSIDE = 'ON_CLICK_OUTSIDE'
export const ON_FOCUS_INPUT = 'ON_FOCUS_INPUT'
export const ON_CHOOSE_PLACE = 'ON_CHOOSE_PLACE'